# Site settings
title: Major Ursa Blog
#email: bartlantz@gmail.com
description: "This is a blog about all of my geeky loves and obsessions: vim and emacs, programming, painting, cats and science fiction."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://majorursa.net" # the base hostname & protocol for your site
twitter_username: bartofdenver
github_username:  majorursa

collections:
  reviews:
    output: true
  notes:
    output: true
  bookreviews:
    output: true

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

